apiVersion: konfigure.giantswarm.io/v1alpha1
kind: ManagementClusterConfiguration
metadata:
  name: collection-konfiguration
  namespace: giantswarm
spec:
  configuration:
    applications:
      excludes: {}
      includes:
        exactMatchers:
          - alloy-gateway
          - app-admission-controller
          - app-exporter
          - app-operator
          - athena
          - aws-resolver-rules-operator
          - aws-vpc-operator
          - capa-iam-operator
          - cloudnative-pg
          - cluster-api
          - cluster-api-events
          - cluster-api-monitoring
          - cluster-api-provider-aws
          - cluster-apps-operator
          - cluster-cleaner
          - dashboards
          - deletion-blocker-operator
          - dex-app
          - dex-operator
          - encryption-provider-operator
          - etcd-backup-operator
          - event-exporter-app
          - exception-recommender
          - falco
          - fluent-logshipping-app
          - gateway-api-bundle
          - grafana
          - happa
          - ingress-nginx
          - irsa-operator
          - keda
          - konfigure-operator
          - kube-downscaler
          - kyverno-policies-connectivity
          - kyverno-policies-dx
          - kyverno-policies-observability
          - kyverno-policies-ux
          - logging-operator
          - loki
          - mimir
          - object-storage-operator
          - observability-operator
          - observability-platform-api
          - organization-operator
          - policy-meta-operator
          - prometheus-remotewrite
          - prometheus-rules
          - pss-operator
          - rbac-operator
          - silence-operator
          - sloth
          - sloth-rules
          - starboard-exporter
          - teleport-operator
          - teleport-tbot
          - trivy
          - trivy-operator
          - upgrade-schedule-operator
    cluster:
      name: "${cluster_name}"
  destination:
    namespace: giantswarm
    naming:
      suffix: "konfiguration"
      useSeparator: true
  reconciliation:
    interval: 1m0s
    retryInterval: 10s
    suspend: false
  sources:
    flux:
      gitRepository:
        name: giantswarm-config
        namespace: flux-giantswarm
      service:
        url: source-controller.flux-giantswarm.svc
