patches:
  - target:
      kind: Konfiguration
      name: collection-konfiguration
      namespace: giantswarm
    patch: |
      - op: add
        path: /spec/targets/defaults/variables/-
        value:
          name: stage
          value: stable
  - path: patches/version-app-operator.yaml
resources:
  - ../../kustomize
